EMG_Bulletins_GC/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.conf import settings
from django.conf.urls.static import static
import bulletins.views
import authentication.views


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', LoginView.as_view(template_name='authentication/login.html', redirect_authenticated_user=True),name='login'),
    path('',authentication.views.login_page,name='login'),
    path('logout/', authentication.views.logout_user, name='logout'),
    #path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('home/', bulletins.views.home, name='home'),

    #gestion des classes

    path('classes/',bulletins.views.classes_list,name='classes_list'),
    path('classesAdmin/',bulletins.views.classes_list_admin,name='classes_list_admin'),
    path('classes/<int:id>',bulletins.views.classe_detail,name='classe_detail'),
    path('classe/<int:idClasse>/<int:idEleve>/remove',bulletins.views.classe_eleve_remove,name='classe_eleve_remove'),
    path('classes/<int:id>/change',bulletins.views.classe_change,name='classe_change'),
    path('classes/<int:id>/delete',bulletins.views.classe_delete,name='classe_delete'),

    #Gestion du journal d'administration
    path('journal/',bulletins.views.journal_list,name='journal_list'),
    path('journal/delete', bulletins.views.journal_delete, name='journal_delete'),

    #gestion des élèves

    path('eleves/admin',bulletins.views.eleves_list_admin,name='eleves_list_admin'),
    path('eleves/',bulletins.views.eleves_list,name='eleves_list'),
    path('anciens_eleves/',bulletins.views.anciens_eleves_list,name='anciens_eleves_list'),
    path('eleves/<int:id>',bulletins.views.eleve_detail,name='eleve_detail'),
    path('eleves/<int:id>/change',bulletins.views.eleve_change,name='eleve_change'),
    path('eleves/<int:id>/delete',bulletins.views.eleve_delete,name='eleve_delete'),

    #configuration des trimestre _ pas d'opérations d'ajout possible

    path('trimestres/change',bulletins.views.trimestres_change,name='trimestres_change'),

    #configuration des absences

    path('absences_retards',bulletins.views.absences_retards_select_list,name='absences_retards'),
    path('absences_retards/<int:idClasse>/<int:idTrimestre>/change',bulletins.views.absences_retards_select_classe_change,name='absences_retards_classe_change'),

    #supervision des absences & retards
    path('absences_retards/admin/', bulletins.views.absences_retards_select_list, name='absences_admin_retards'),
    path('absences_retards/admin/<int:idClasse>/<int:idTrimestre>/change',bulletins.views.absences_retards_select_classe_change, name='absences_admin_retards_classe_change'),

    #Configuration des exportations et importations en CSV

    path('export_csv',bulletins.views.export_csv,name='export_csv'),
    path('export_csv/eleves',bulletins.views.export_csv_eleves,name='export_eleves_csv'),
    path('export_csv/journal', bulletins.views.export_csv_journal, name='export_journal_csv'),
    path('export_csv/eleves_actifs', bulletins.views.export_csv_eleves_actifs, name='export_eleves_actifs_csv'),
    path('export_csv/disciplines', bulletins.views.export_csv_disciplines, name='export_disciplines_csv'),
    path('export_csv/disciplines_actives', bulletins.views.export_csv_disciplines_actives, name='export_disciplines_actives_csv'),
    path('export_csv/stages_actives',bulletins.views.export_csv_stages_actives,name='export_stages_actives_csv'),
    path('export_csv/stages',bulletins.views.export_csv_stages,name='export_stages_csv'),
    path('export_csv/appreciations', bulletins.views.export_csv_appreciations, name='export_appreciations_csv'),
    path('export_csv/appreciations_actives', bulletins.views.export_csv_appreciations_actives, name='export_appreciations_actives_csv'),
    path('import_csv',bulletins.views.import_csv,name='import_csv'),
    path('import_csv/eleves/',bulletins.views.import_eleve_csv,name='import_csv_eleves'),
    path('import_csv/stages/', bulletins.views.import_stage_csv, name='import_csv_stages'),
    path('import_csv/projets/', bulletins.views.import_projet_csv, name='import_csv_projets'),
    path('import_csv/disciplines/', bulletins.views.import_discipline_csv, name='import_csv_disciplines'),
    path('import_csv/appreciations/', bulletins.views.import_appreciation_csv, name='import_csv_appreciations'),

    #Enseignements (Consultation)

    path('disciplines',bulletins.views.disciplines_list,name='disciplines_liste'),
    path('my_disciplines',bulletins.views.my_disciplines_list,name='my_disciplines_liste'),
    path('disciplines/add', bulletins.views.discipline_add, name='discipline_add'),
    path('disciplines/<int:idDiscipline>/delete', bulletins.views.discipline_delete, name='discipline_delete'),
    path('disciplines/<int:idDiscipline>/evaluate', bulletins.views.discipline_evaluate, name='discipline_evaluate'),
    path('disciplines/<int:idDiscipline>/change', bulletins.views.discipline_change, name='discipline_change'),
    path('disciplines/<int:idDiscipline>/eleve/change', bulletins.views.disciplineEleve_change,name='discipline_eleve_change'),
    path('disciplines/<int:idDiscipline>/eleve/detail', bulletins.views.disciplineEleve_detail,name='discipline_eleve_detail'),
    path('disciplines/<int:idDiscipline>/detail', bulletins.views.discipline_detail, name='discipline_detail'),

    #Enseignements (Supervision)
    path('disciplines/admin', bulletins.views.disciplines_list_admin, name='disciplines_liste_admin'),
    path('disciplines/admin/<int:idDiscipline>/eleve/detail', bulletins.views.disciplineEleve_detail,name='discipline_admin_eleve_detail'),
    path('disciplines/admin/<int:idDiscipline>/eleve/change', bulletins.views.disciplineEleve_change,name='discipline_admin_eleve_change'),
    path('discipline/admin/<int:idDiscipline>/evaluate', bulletins.views.discipline_evaluate,name='discipline_admin_evaluate'),
    path('disciplines/admin/<int:idDiscipline>/change', bulletins.views.discipline_change, name='discipline_admin_change'),
    path('disciplines/admin/<int:idDiscipline>/delete', bulletins.views.discipline_delete, name='discipline_admin_delete'),

    #Les corrections - des disciplines, les stages et les projets
    path('corrections/',bulletins.views.corrections_list,name='corrections_liste'),
    path('my_corrections/', bulletins.views.my_corrections_list, name='my_corrections_liste'),
    path('corrections/<int:idDiscipline>/',bulletins.views.correction_discipline_detail,name='correction_discipline_detail'),
    path('corrections/stages/<int:idStage>/', bulletins.views.correction_stage_detail,name='correction_stage_detail'),
    path('corrections/projets/<int:idProjet>/', bulletins.views.correction_projet_detail,name='correction_projet_detail'),
    path('my_corrections/<int:idDiscipline>/',bulletins.views.my_correction_discipline_detail,name='my_correction_discipline_detail'),
    path('my_corrections/stages/<int:idStage>/', bulletins.views.my_correction_stage_detail,name='my_correction_stage_detail'),
    path('my_corrections/projets/<int:idProjet>/', bulletins.views.my_correction_projet_detail,name='my_correction_projet_detail'),

    path('my_corrections/<int:idDiscipline>/delete',bulletins.views.my_correction_discipline_delete,name='my_correction_delete'),
    path('my_corrections/stages/<int:idStage>/delete', bulletins.views.my_correction_stage_delete,name='my_correction_stage_delete'),
    path('my_corrections/projets/<int:idProjet>/delete', bulletins.views.my_correction_projet_delete,name='my_correction_projet_delete'),

    #Corrections (Supervision)
    path('my_corrections/admin/', bulletins.views.admin_corrections_list, name='corrections_admin_liste'),
    path('my_corrections/admin/<int:idDiscipline>/', bulletins.views.my_correction_discipline_detail,name='my_correction_discipline_admin_detail'),
    path('my_corrections/admin/<int:idDiscipline>/delete', bulletins.views.my_correction_discipline_delete,name='my_correction_admin_delete'),
    path('my_corrections/admin/stages/<int:idStage>/', bulletins.views.my_correction_stage_detail,name='my_correction_stage_admin_detail'),
    path('my_corrections/admin/projets/<int:idProjet>/', bulletins.views.my_correction_projet_detail,name='my_correction_projet_admin_detail'),
    path('my_corrections/admin/stages/<int:idStage>/delete', bulletins.views.my_correction_stage_delete,name='my_correction_admin_stage_delete'),
    path('my_corrections/admin/projets/<int:idProjet>/delete', bulletins.views.my_correction_projet_delete,name='my_correction_admin_projet_delete'),

    #AvisCollège

    path('avisCollege/add', bulletins.views.avis_college_add,name='avis_college_add'),
    path('avisCollege/<int:idAvis>/delete',bulletins.views.avis_college_delete,name='avis_college_delete'),
    path('avisCollege/<int:idAvis>/change',bulletins.views.avis_college_change,name='avis_college_change'),
    path('avisCollege/',bulletins.views.avis_college_list,name='avis_college_liste'),

    #AvisCollege (supervision)
    path('avisCollege/admin/', bulletins.views.avis_college_admin_list, name='avis_college_admin_liste'),
    path('avisCollege/admin/<int:idAvis>/change', bulletins.views.avis_college_change, name='avis_college_admin_change'),
    path('avisCollege/admin/<int:idAvis>/delete', bulletins.views.avis_college_delete, name='avis_college_admin_delete'),

    #Gestion projets
    path('projets/',bulletins.views.projets_list,name='projets_liste'),
    path('my_projets/', bulletins.views.my_projets_list, name='my_projets_liste'),
    path('projets/add',bulletins.views.projets_add,name='projets_add'),
    path('projets/<int:idProjet>/change',bulletins.views.projets_change,name='projets_change'),
    path('projets/<int:idProjet>/delete', bulletins.views.projets_delete, name='projets_delete'),

    #Gestion projets (admin)

authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    ROLE_CHOICES = (
        ('ADMIN', 'Administrateur'),
        ('PROF', 'Professeur'),
        ('INFO','Visiteur'),
    )
    role = models.CharField(max_length=30, choices=ROLE_CHOICES, verbose_name='Rôle')

    def __str__(self):
        return f'{self.first_name} {self.last_name}'
    
    def nom_court(self):
        return f"{self.first_name[0]}. {self.last_name}"

authentication/forms.py
# authentication/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(max_length=63, widget=forms.TextInput(attrs={'placeholder': 'Identifiant'}))
    password = forms.CharField(max_length=63, widget=forms.PasswordInput(attrs={'placeholder': 'Mot de passe'}))

authentication/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from . import forms
from . import models
from django.contrib.auth import login, authenticate, logout # import des fonctions login et authenticate
from bulletins.models import Journal
def login_page(request):
    form = forms.LoginForm()
    message = ''
    if request.method == 'POST':
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password'],
            )
            if user is not None:
                login(request, user)
                log=Journal(utilisateur=request.user,message='connexion')
                log.save()
                return redirect('home')
            else:
                message = 'Identifiants invalides.'
    return render(
        request, 'authentication/login.html', context={'form': form, 'message': message})

@login_required
def enseignants_list(request):
    enseignants=models.User.objects.all().order_by('last_name')
    return render(request,'authentication/enseignants_list.html',context={"enseignants":enseignants})

@login_required
def myProfil(request):
    return render(request,'authentication/my_profil.html')

@login_required
def logout_user(request):
    log = Journal(utilisateur=request.user, message='déconnexion')
    log.save()
    logout(request)
    return redirect('login')

authentication/templates/authentication/enseignants_list.html
{% extends 'base.html' %}
{% load bulletins_extras %}
{% block breadcrumb%}
<li class="breadcrumb-item"><a href="{% url 'home' %}" class="link-secondary link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">Accueil</a></li>
<li class="breadcrumb-item active" aria-current="page" class="text-secondary">Enseignants</li>

{% endblock breadcrumb%}
{% block content %}
<div class="container-fluid container-md">
    <div class="row">
        <div class="col-12 mt-4">
              <h1 class="mb-2">Enseignants</h1>
    
            <fieldset class="rounded shadow mb-3 p-3">
                <p class="fs-4">Important</p>
    
                <p>Cette page permet uniquement de visualiser les informations sur les enseignants et utilisateurs enregistrés dans la base. Pour des opérations de modification, création, suppression etc., il faut passer par la page d'administration du site.</p>
            </fieldset>
    
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Nom</th>
                        <th>Prénom</th>
                        <th>Login</th>
                        <th>Mail</th>
                        <th>Role</th>
                        <th>Statut</th>
                        <th>Dernière connexion</th>
                    </tr>
                </thead>
                <tbody>
                    {% for enseignant in enseignants%}
                    <tr>
                        <th>{{enseignant.last_name}}</th>
                        <th>{{enseignant.first_name}}</th>
                        <td>{{enseignant.username}}</td>
                        <td>{{enseignant.email}}</td>
                        <td>{{enseignant.get_role_display}}</td>
                        <td>{{enseignant.is_active|yesno:"Actif,Inactif,Non défini"}}</td>
                        <td>{{enseignant.last_login|default_if_none:"jamais"}}</td>    
                    </tr>
                    {% endfor %}
    
                </tbody>
    
            </table>
        </div>
    </div>
</div>

{% endblock content %}

authentication/templates/authentication/login.html
{% load static %}
{% load bulletins_extras %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html class="height100">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>EMG - Bulletins</title>
        <meta name="description" content="">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Quicksand">
        <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.21.4/dist/bootstrap-table.min.css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
        <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}" >
        <!-- Font Awesome -->
        <script src="https://kit.fontawesome.com/14273d579a.js" crossorigin="anonymous"></script>
    </head>
    <body class="d-flex align-items-center bg-image">
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <!-- Bootstrap JS bundle -->                
                
                <main class="form-signin w-100 m-auto">
                  <form method="post">
                    {% csrf_token %}
                    {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                    {% endfor %}
                    <img class="mb-3" src="{% static 'images/Logo_EMG_3.png' %}" alt="École Mathias Grünewald">

                      <div class="row">
                        <div class="col-12 col-lg-10 offset-lg-1 col-xl-8 offset-xl-2 text-center">
                          <div class="form-floating mb-3 m-auto">
                      
                            {{form.username|add_classes:'form-control'}}
                            <label for="{{form.username.id_for_label}}"">Identifiant</label>
                          </div>
                          <div class="form-floating mb-3 m-auto">
                            {{form.password|add_classes:'form-control'}}
                            <label for="{{form.password.id_for_label}}">Mot de passe</label>
                          </div>
                      
                          {% if message %}
                          <ul class="mb-2 list-group list-group-flush">
                            <li class="rounded list-group-item list-group-item-warning">{{ message }}</li>
                          </ul>
                          {% endif %}
                          <button class="btn btn-lg btn-primary m-auto" type="submit">Connexion</button>
                        </div>
                      </div>
                     
                      
                  </form>
                  </main>
              </div>
              
          <!-- Script js -->
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
          crossorigin="anonymous"></script>

    </body>
</html>

authentication/templates/authentication/my_profil.html
{% extends 'base.html' %}
{% load bulletins_extras %}
{% block breadcrumb%}
<li class="breadcrumb-item"><a href="{% url 'home' %}" class="link-secondary link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">Accueil</a></li>
<li class="breadcrumb-item active" aria-current="page" class="text-secondary">Mon profil</li>
{% endblock breadcrumb%}

{% block content %}
<div class="container-fluid container-md">
    <div class="row">
        <div class="col-12 col-lg-11 col-xl-10 mt-4">
              <h1 class="mb-4">{{ user.first_name }} {{ user.last_name }}</h1>

                  <table class="table table-striped">
                    <tbody>
                        <tr>
                            <td>Identifiant :</td>
                            <td><strong>{{user.username}}</strong></td>
                        </tr>
                        <tr>
                            <td>Statut : </td>
                            <td><strong>{{user.is_active|yesno:"en activité,inactif,non défini"}}</strong></td>
                        </tr>
                        <tr>
                            <td>Email : </td>
                            <td><strong>{{user.email}}</strong></td>
                        </tr>
                        <tr>
                            <td>Profil : </td>
                            <td><strong>{{user.get_role_display}}</strong></td>
                        </tr>
                        <tr>
                            <td>Dernière connexion : </td>
                            <td><strong>{{user.last_login}}</strong></td>
                        </tr>
        
                    </tbody>
        
                </table>


        </div>
    </div>
</div>

{% endblock content %}